# Generated by Django 2.1.4 on 2019-02-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190124_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
